### ISSUE TITLE
Question: How to import single component's css?

### ISSUE THREAD

**Issue by Munawwar** [wangdicoder/tiny-ui#32]
Firstly: Good library. Looks nice.

Question: I see the index.min.css to be around 150 kb (uncompressed). But I wont use all the components.
How do I import one/few components CSS only (or even sass file directly)?

**Comment by Munawwar** [comment]
I figured it out. I was thinking something was wrong when I saw this message:

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
101 │ $headings-margin-bottom: $spacer / 2          !default;
    │                          ^^^^^^^^^^^
    ╵
    node_modules/tiny-ui/lib/style/_variables.scss 101:26  @import
    node_modules/tiny-ui/lib/button/style/_index.scss 1:9  root stylesheet
```

But it is just a warning, and not an error. Thanks.

I am trying it out with preact + vite -> https://github.com/Munawwar/preact-vite-spa-starter-template/tree/tiny-ui

**Comment by Munawwar** [comment]
@wangdicoder my mention of tiny-ui on twitter got some attention  🙂
https://mobile.twitter.com/_developit/status/1511832615120261124

**Comment by wangdicoder** [comment]
> @wangdicoder my mention of tiny-ui on twitter got some attention (e.g. from preact's author) 🙂 https://mobile.twitter.com/_developit/status/1511832615120261124

Wow, amazing! Thanks man
